### ISSUE TITLE
Implementing Simpler Package Structure

### ISSUE THREAD

**Issue by aritraroy** [DhayanandBaskar/Elegant-Algorithms#1]
Can we have a simpler and cleaner package structure like this,

Top-level packages ->
1) algorithms
2) dataStructures
3) utils

Details - 
1) All the algorithms can reside in the algorithms package. There can be further packages inside it for different types like dynamicProgramming, etc.

2) All data structures can be kept inside dataStructures package.

3) All common utilities can be shared by these packages.

**Comment by DhayanandBaskar** [comment]
Sure, I will make the changes and push. Thanks.

**Comment by aritraroy** [comment]
It is resolved. Closing.
