### ISSUE TITLE
Changing Repository Name

### ISSUE THREAD

**Issue by aritraroy** [DhayanandBaskar/Elegant-Algorithms#2]
This repository will have both algorithms and data structures, so the name "Elegant-Algorithms" won't be appropriate.

Let's have a new name which conveys both DS and Algo in it.

Starting with some ideas -
1) elegant-algo-ds
2) algo-ds-simplified
3) ultimate-algo-ds-reference

**Comment by DhayanandBaskar** [comment]
The first option seems more apt to the current progress of the repo but eventually, we should move towards the 3rd option so can we rename this to the third option?

**Comment by aritraroy** [comment]
Yes, let's go with it. The 3rd one will make more sense in the future. Please make the change and close this issue.

**Comment by DhayanandBaskar** [comment]
Yes, sure.
